Bndw/format translations
bndw/wifi-card pull request #149
Opened 2021-07-29 18:56 UTC by bndw

- Clean up formatting and sort order of language dropdown (https://github.com/bndw/wifi-card/issues/80)
  - `latinName - nativeName` format to account for `RTL` languages
  - Sort by latin name
- Use a generic English translation

2021-07-29 19:10 UTC, Andanan commented on src/App.js
> +          <option value="de-DE">German - Germany</option>
```suggestion
          <option value="de-DE">German - Deutsch</option>
```

2021-07-29 19:20 UTC, A-Tokyo requested changes

2021-07-29 19:20 UTC, A-Tokyo commented on src/App.js
> +          <option value="pt-BR">Portuguese - Brazil</option>
```suggestion
          <option value="pt-BR">Portuguese - Português brasileiro</option>
```

2021-07-30 00:30 UTC, A-Tokyo approved these changes

2021-07-30 01:14 UTC, Baoyuantop approved these changes

2021-07-30 15:10 UTC, merged